import {MigrationInterface, QueryRunner} from "typeorm";

export class makeApplicationPropertiesNullableForPartners1607177266696 implements MigrationInterface {
    name = 'makeApplicationPropertiesNullableForPartners1607177266696'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "city" text`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "state" text`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "street"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "street" text`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "zip_code"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "zip_code" text`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "type" text`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "other_type"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "other_type" text`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "first_name" text`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "last_name" text`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "agency"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "agency" text`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "phone_number" text`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "email_address"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "email_address" text`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "first_name" text`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "middle_name"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "middle_name" text`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "last_name" text`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "birth_month"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "birth_month" text`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "birth_day"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "birth_day" text`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "birth_year"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "birth_year" text`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "email_address"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "email_address" text`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "no_email" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "phone_number" text`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "phone_number_type"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "phone_number_type" text`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "no_phone" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "demographics" DROP COLUMN "ethnicity"`);
        await queryRunner.query(`ALTER TABLE "demographics" ADD "ethnicity" text`);
        await queryRunner.query(`ALTER TABLE "demographics" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "demographics" ADD "gender" text`);
        await queryRunner.query(`ALTER TABLE "demographics" DROP COLUMN "sexual_orientation"`);
        await queryRunner.query(`ALTER TABLE "demographics" ADD "sexual_orientation" text`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "first_name" text`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "middle_name"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "middle_name" text`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "last_name" text`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "birth_month"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "birth_month" text`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "birth_day"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "birth_day" text`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "birth_year"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "birth_year" text`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "email_address"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "email_address" text`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "phone_number" text`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "phone_number_type"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "phone_number_type" text`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "app_url" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "additional_phone" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "additional_phone_number"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "additional_phone_number" text`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "additional_phone_number_type"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "additional_phone_number_type" text`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "household_size" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "housing_status"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "housing_status" text`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "send_mail_to_mailing_address" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "income_vouchers" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "income"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "income" text`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "income_period" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "accepted_terms" DROP NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "accepted_terms" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "income_period" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "income"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "income" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "income_vouchers" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "send_mail_to_mailing_address" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "housing_status"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "housing_status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "household_size" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "additional_phone_number_type"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "additional_phone_number_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "additional_phone_number"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "additional_phone_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "additional_phone" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "app_url" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "phone_number_type"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "phone_number_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "phone_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "email_address"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "email_address" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "birth_year"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "birth_year" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "birth_day"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "birth_day" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "birth_month"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "birth_month" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "middle_name"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "middle_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "household_member" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "household_member" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "demographics" DROP COLUMN "sexual_orientation"`);
        await queryRunner.query(`ALTER TABLE "demographics" ADD "sexual_orientation" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "demographics" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "demographics" ADD "gender" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "demographics" DROP COLUMN "ethnicity"`);
        await queryRunner.query(`ALTER TABLE "demographics" ADD "ethnicity" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "no_phone" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "phone_number_type"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "phone_number_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "phone_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "no_email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "email_address"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "email_address" character varying`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "birth_year"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "birth_year" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "birth_day"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "birth_day" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "birth_month"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "birth_month" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "middle_name"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "middle_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "email_address"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "email_address" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "phone_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "agency"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "agency" character varying`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "other_type"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "other_type" character varying`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "alternate_contact" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "zip_code"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "zip_code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "street"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "street" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "state" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "city" character varying NOT NULL`);
    }

}
