// The names of supported filters on /listings
export enum ListingFilterKeys {
  id = "id",
  status = "status",
  name = "name",
  isVerified = "isVerified",
  bedrooms = "bedrooms",
  zipcode = "zipcode",
  availability = "availability",
  program = "program",
  minRent = "minRent",
  maxRent = "maxRent",
  minAmiPercentage = "minAmiPercentage",
  leasingAgents = "leasingAgents",
  elevator = "elevator",
  wheelchairRamp = "wheelchairRamp",
  serviceAnimalsAllowed = "serviceAnimalsAllowed",
  accessibleParking = "accessibleParking",
  parkingOnSite = "parkingOnSite",
  inUnitWasherDryer = "inUnitWasherDryer",
  laundryInBuilding = "laundryInBuilding",
  barrierFreeEntrance = "barrierFreeEntrance",
  rollInShower = "rollInShower",
  grabBars = "grabBars",
  heatingInUnit = "heatingInUnit",
  acInUnit = "acInUnit",
  jurisdiction = "jurisdiction",
  favorited = "favorited",
  marketingType = "marketingType",
  hearing = "hearing",
  mobility = "mobility",
  visual = "visual",
  vacantUnits = "vacantUnits",
  openWaitlist = "openWaitlist",
  closedWaitlist = "closedWaitlist",
  Families = "Families",
  ResidentswithDisabilities = "ResidentswithDisabilities",
  Seniors55 = "Seniors55",
  Seniors62 = "Seniors62",
  SupportiveHousingfortheHomeless = "SupportiveHousingfortheHomeless",
  Veterans = "Veterans",
  region = "region",
  bedRoomSize = "bedRoomSize",
  communityPrograms = "communityPrograms",
  accessibility = "accessibility",
  barrierFreeUnitEntrance = "barrierFreeUnitEntrance",
  loweredLightSwitch = "loweredLightSwitch",
  barrierFreeBathroom = "barrierFreeBathroom",
  wideDoorways = "wideDoorways",
  loweredCabinets = "loweredCabinets",
}

export enum AvailabilityFilterEnum {
  hasAvailability = "hasAvailability",
  noAvailability = "noAvailability",
  waitlist = "waitlist",
}
