extensions:
  sigv4auth:
    service: "aps"

service:
  extensions: [sigv4auth]
  telemetry:
    logs:
      level: info
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      exporters: [prometheusremotewrite]
    metrics/ecs:
      receivers: [awsecscontainermetrics]
      processors: [transform/ecs]
      exporters: [prometheusremotewrite]

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  prometheus:
    config:
      scrape_configs:
        - job_name: 'prisma_metrics'
          scrape_interval: 10s
          metrics_path: /prisma_metrics
          static_configs:
            - targets: ['0.0.0.0:3100']
  awsecscontainermetrics:
    collection_interval: 10s

processors:
  transform/ecs:
    metric_statements:
    - context: resource
      statements:
      - keep_keys(attributes, ['aws.ecs.task.family', 'aws.ecs.task.id', 'container.name', 'aws.ecs.container.exit_code'])

exporters:
  prometheusremotewrite:
    endpoint: ${env:PROMETHEUS_REMOTE_WRITE_ENDPOINT}
    auth:
      authenticator: sigv4auth
    resource_to_telemetry_conversion:
      enabled: true
