export enum ListingFilterKeys {
  accessibilityPriorityTypes = 'accessibilityPriorityTypes',
  availabilities = 'availabilities',
  availability = 'availability',
  bathrooms = 'bathrooms',
  bedrooms = 'bedrooms',
  bedroomTypes = 'bedroomTypes',
  city = 'city',
  configurableRegions = 'configurableRegions',
  counties = 'counties',
  homeTypes = 'homeTypes',
  ids = 'ids',
  isVerified = 'isVerified',
  jurisdiction = 'jurisdiction',
  leasingAgent = 'leasingAgent',
  listingFeatures = 'listingFeatures',
  listingType = 'listingType',
  monthlyRent = 'monthlyRent',
  multiselectQuestions = 'multiselectQuestions',
  name = 'name',
  neighborhood = 'neighborhood',
  parkingType = 'parkingType',
  regions = 'regions',
  reservedCommunityTypes = 'reservedCommunityTypes',
  section8Acceptance = 'section8Acceptance',
  status = 'status',
  zipCode = 'zipCode',
}
