export enum ListingFilterKeys {
  availability = 'availability',
  bathrooms = 'bathrooms',
  bedrooms = 'bedrooms',
  city = 'city',
  counties = 'counties',
  homeTypes = 'homeTypes',
  ids = 'ids',
  isVerified = 'isVerified',
  jurisdiction = 'jurisdiction',
  leasingAgent = 'leasingAgent',
  listingFeatures = 'listingFeatures',
  monthlyRent = 'monthlyRent',
  name = 'name',
  neighborhood = 'neighborhood',
  regions = 'regions',
  reservedCommunityTypes = 'reservedCommunityTypes',
  section8Acceptance = 'section8Acceptance',
  status = 'status',
  zipCode = 'zipCode',
}
