export enum ListingFilterKeys {
  status = 'status',
  name = 'name',
  neighborhood = 'neighborhood',
  bedrooms = 'bedrooms',
  bathrooms = 'bathrooms',
  zipcode = 'zipcode',
  leasingAgents = 'leasingAgents',
  jurisdiction = 'jurisdiction',
  city = 'city',
  counties = 'counties',
  monthlyRent = 'monthlyRent',
  isExternal = 'isExternal',
  availability = 'availability',
  ids = 'ids',
}
