export const stateKeys = [
  "",
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "DC",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
]

export const contactPreferencesKeys = [
  {
    id: "email",
  },
  {
    id: "phone",
  },
  {
    id: "letter",
  },
  {
    id: "text",
  },
]

export const relationshipKeys = [
  "",
  "spouse",
  "registeredDomesticPartner",
  "parent",
  "child",
  "sibling",
  "cousin",
  "aunt",
  "uncle",
  "nephew",
  "niece",
  "grandparent",
  "greatGrandparent",
  "inLaw",
  "friend",
  "other",
]

export const altContactRelationshipKeys = [
  "familyMember",
  "friend",
  "caseManager",
  "other",
  "noContact",
]

export const ethnicityKeys = ["hispanicLatino", "notHispanicLatino"]

export const raceKeys = [
  "americanIndianAlaskanNative",
  "asian",
  "blackAfricanAmerican",
  "nativeHawaiianOtherPacificIslander",
  "white",
  "americanIndianAlaskanNativeAndBlackAfricanAmerican",
  "americanIndianAlaskanNativeAndWhite",
  "asianAndWhite",
  "blackAfricanAmericanAndWhite",
  "otherMutliracial",
]

export const genderKeys = [
  "female",
  "male",
  "genderqueerGenderNon-Binary",
  "transFemale",
  "transMale",
  "notListed",
]

export const sexualOrientation = [
  "bisexual",
  "gayLesbianSameGenderLoving",
  "questioningUnsure",
  "straightHeterosexual",
  "notListed",
]

export const howDidYouHear = [
  {
    id: "alamedaCountyHCDWebsite",
  },
  {
    id: "developerWebsite",
  },
  {
    id: "flyer",
  },
  {
    id: "emailAlert",
  },
  {
    id: "friend",
  },
  {
    id: "housingCounselor",
  },
  {
    id: "radioAd",
  },
  {
    id: "busAd",
  },
  {
    id: "other",
  },
]

export const phoneNumberKeys = ["work", "home", "cell"]

export const preferredUnit = [
  {
    id: "studio",
  },
  {
    id: "oneBedroom",
  },
  {
    id: "twoBedroom",
  },
  {
    id: "threeBedroom",
  },
  {
    id: "moreThanThreeBedroom",
  },
]

export const bedroomKeys = ["studio", "oneBdrm", "twoBdrm", "threeBdrm"]

export const neighborhoodKeys = ["", "AirportSub",
"ArdenPark",
"AviationSub",
"Bagley",
"BartonMcFarland",
"BelleIsle",
"Belmont",
"BergLahser",
"BethuneCommunity",
"BostonEdison",
"Boynton",
"BrewsterHomes",
"Brightmoor", 
"BrushPark",
"BuffaloCharles",
"Butler",
"CadillacCommunity",
"CadillacHeights",
"CampauBanglatown",
"CarbonWorks",
"CastleRouge",
"CentralSouthwest",
"ChadseyCondon",
"Chalfonte",
"ChandlerChalmers",
"ChandlerPark",
"Claytown",
"CollegePark",
"ConantGardens",
"ConnerCreek",
"ConnerCreekIndustrial",
"CoreCity",
"Corktown",
"CornerstoneVillage",
"CraryStMarys",
"CulturalCenter",
"Davison",
"DavisonSchoolcraft",
"Delray",
"Denby",
"DetroitGolf",
"DexterFenkell",
"DexterLinwood",
"Douglass",
"Downtown",
"EastCanfield",
"EastEnglishVillage",
"EastVillage",
"EasternMarket",
"EdenGardens",
"ElijahMcCoy",
"ElizaHowell",
"ElmwoodPark", 
"EvergreenLahser",
"EvergreenOuterDrive",
"FarWestDetroit",
"Fiskhorn",
"FitzgeraldMarygrove",
"FivePoints",
"ForestPark",
"FoxCreek", 
"Franklin",
"FranklinPark",
"GardenHomes",
"GardenView",
"GatewayCommunity",
"GoldCoast",
"GrandRiverI",
"GrandRiverStMarys",
"Grandmont",
"Grandmont1",
"Grant",
"GratiotGrand",
"GratiotKettering",
"GratiotWebpage",
"GratiotWoods",
"Greektown",
"GreenAcres",
"Greenfield",
"GreenfieldGrand",
"GreenfieldPark",
"GrixdaleFarms",
"HappyHomes",
"HarmonyVillage",
"HawthornePark",
"Historic Atkinson",
"HolcombCommunity",
"HubbardFarms",
"HubbardRichard",
"HubbellLyndon",
"HubbellPuritan",
"IndianVillage",
"Islandview", 
"Jamison",
"JeffersonChalmers",
"Jeffries",
"JosephBerry",
"JoyCommunity",
"JoySchaefer",
"LaSalleGardens",
"LaSallePark",
"LafayettePark",
"LittlefieldCommunity",
"Mapleridge",
"MarinaDistrict",
"MartinPark",
"McDougallHunt",
"McNicholsEvergreen",
"MedburyPark",
"MedicalCenter",
"MelvernHill",
"Mexicantown",
"MichiganMartin",
"Midtown", 
"Midwest",
"MillerGrove",
"MilwaukeeJunction",
"MinockPark",
"MohicanRegent",
"Morningside",
"MorossMorang",
"MountOlivet",
"NWGoldberg",
"NardinPark",
"NewCenter",
"NewCenterCommons",
"Nolan",
"NorthCampau",
"NorthCorktown",
"NorthEnd",
"NorthRosedalePark" ,
"NortheastCentralDistrict",
"NorthwestCommunity",
"Nortown",
"OakGrove",
"OakmanBlvd",
"OakwoodHeights",
"OhairPark",
"OldRedford",
"Other",
"OuterDriveHayes",
"PalmerPark",
"PalmerWoods",
"Paveway",
"Penrose",
"Pershing",
"PetsokeyOtsego",
"PietyHill",
"PilgrimVillage",
"PingreePark",
"PlymouthHubbell",
"PlymouthI",
"PoletownEast",
"PrideArea",
"Pulaski",
"Ravendale",
"RegentPark",
"Riverbend",
"Riverdale",
"Rivertown",
"RosedalePark",
"RougePark",
"RussellIndustrial",
"RussellWoods",
"SanBernardo",
"SchaeferLodge",
"SchoolcraftSouthfield",
"SevenMile",
"SevenMileLodge",
"Sherwood",
"SherwoodForest",
"SouthOfSix",
"SouthfieldPlymouth",
"Springwells",
"StateFair",
"TechTown",
"TheEye",
"TriPoint",
"UniversityDistrict",
"VirginiaPark",
"VirginiaParkCommunity",
"VonSteuben",
"Wade",
"WarrenAve",
"Warrendale",
"WaterworksPark",
"WayneState",
"WeCareCommunity",
"Weatherby",
"WestEnd",
"WestOuterDrive",
"WestSideIndustrial",
"WestVillage",
"WestwoodPark",
"WildemerePark",
"Winship",
"Woodbridge",
"YorkshireWoods",
].sort((a, b) =>
a.localeCompare(b)
);
