export const stateKeys = [
  "",
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "DC",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
]

export const contactPreferencesKeys = [
  {
    id: "email",
  },
  {
    id: "phone",
  },
  {
    id: "letter",
  },
  {
    id: "text",
  },
]

export const relationshipKeys = [
  "",
  "spouse",
  "registeredDomesticPartner",
  "parent",
  "child",
  "sibling",
  "cousin",
  "aunt",
  "uncle",
  "nephew",
  "niece",
  "grandparent",
  "greatGrandparent",
  "inLaw",
  "friend",
  "other",
]

export const altContactRelationshipKeys = [
  "familyMember",
  "friend",
  "caseManager",
  "other",
  "noContact",
]

export const ethnicityKeys = ["hispanicLatino", "notHispanicLatino"]

export const raceKeys = [
  "americanIndianAlaskanNative",
  "asian",
  "blackAfricanAmerican",
  "nativeHawaiianOtherPacificIslander",
  "white",
  "americanIndianAlaskanNativeAndBlackAfricanAmerican",
  "americanIndianAlaskanNativeAndWhite",
  "asianAndWhite",
  "blackAfricanAmericanAndWhite",
  "otherMutliracial",
]

export const genderKeys = [
  "female",
  "male",
  "genderqueerGenderNon-Binary",
  "transFemale",
  "transMale",
  "notListed",
]

export const sexualOrientation = [
  "bisexual",
  "gayLesbianSameGenderLoving",
  "questioningUnsure",
  "straightHeterosexual",
  "notListed",
]

export const howDidYouHear = [
  {
    id: "alamedaCountyHCDWebsite",
  },
  {
    id: "developerWebsite",
  },
  {
    id: "flyer",
  },
  {
    id: "emailAlert",
  },
  {
    id: "friend",
  },
  {
    id: "housingCounselor",
  },
  {
    id: "radioAd",
  },
  {
    id: "busAd",
  },
  {
    id: "other",
  },
]

export const phoneNumberKeys = ["work", "home", "cell"]

export const preferredUnit = [
  {
    id: "studio",
  },
  {
    id: "oneBedroom",
  },
  {
    id: "twoBedroom",
  },
  {
    id: "threeBedroom",
  },
  {
    id: "moreThanThreeBedroom",
  },
]

export const bedroomKeys = ["studio", "oneBdrm", "twoBdrm", "threeBdrm"]

export const neighborhoodKeys = [
  "",
  "Midtown",
  "ElmwoodPark",
  "Islandview",
  "Brightmoor",
  "FoxCreek",
  "FivePoints",
  "TheEye",
  "SouthOfSix",
  "SevenMile",
  "OakGrove",
  "Riverdale",
  "BergLahser",
  "MelvernHill",
  "OldRedford",
  "EvergreenLahser",
  "HolcombCommunity",
  "McNicholsEvergreen",
  "MillerGrove",
  "OhairPark",
  "EvergreenOuterDrive",
  "NorthRosedalePark",
  "ElizaHowell",
  "CastleRouge",
  "MinockPark",
  "RosedalePark",
  "WestwoodPark",
  "Grandmont1",
  "Grandmont",
  "SchoolcraftSouthfield",
  "GreenfieldGrand",
  "GrandRiverStMarys",
  "CraryStMarys",
  "HubbellPuritan",
  "Belmont",
  "HubbellLyndon",
  "CadillacCommunity",
  "Greenfield",
  "CollegePark",
  "SanBernardo",
  "SevenMileLodge",
  "SchaeferLodge",
  "Winship",
  "TriPoint",
  "HarmonyVillage",
  "GardenHomes",
  "Bagley",
  "FitzgeraldMarygrove",
  "BethuneCommunity",
  "Chalfonte",
  "GreenAcres",
  "SherwoodForest",
  "UniversityDistrict",
  "MartinPark",
  "PilgrimVillage",
  "DexterFenkell",
  "PalmerWoods",
  "DetroitGolf",
  "PalmerPark",
  "StateFair",
  "Penrose",
  "GrixdaleFarms",
  "Nolan",
  "HawthornePark",
  "GreenfieldPark",
  "CadillacHeights",
  "NorthCampau",
  "CampauBanglatown",
  "Butler",
  "Pershing",
  "NortheastCentralDistrict",
  "ConantGardens",
  "Davison",
  "BuffaloCharles",
  "Sherwood",
  "Nortown",
  "Grant",
  "AirportSub",
  "ConnerCreek",
  "Pulaski",
  "MountOlivet",
  "VonSteuben",
  "MohicanRegent",
  "Franklin",
  "RegentPark",
  "Mapleridge",
  "LaSallePark",
  "GratiotWebpage",
  "EdenGardens",
  "OuterDriveHayes",
  "Denby",
  "MorossMorang",
  "YorkshireWoods",
  "Wade",
  "Ravendale",
  "CornerstoneVillage",
  "EastEnglishVillage",
  "Morningside",
  "ChandlerPark",
  "ChandlerChalmers",
  "WestEnd",
  "EastCanfield",
  "EastVillage",
  "ConnerCreekIndustrial",
  "Riverbend",
  "JeffersonChalmers",
  "DexterLinwood",
  "GatewayCommunity",
  "BostonEdison",
  "ArdenPark",
  "Historic Atkinson",
  "PetsokeyOtsego",
  "Jamison",
  "WildemerePark",
  "NWGoldberg",
  "ElijahMcCoy",
  "LaSalleGardens",
  "VirginiaParkCommunity",
  "VirginiaPark",
  "PietyHill",
  "NewCenterCommons",
  "NewCenter",
  "TechTown",
  "NorthEnd",
  "RussellIndustrial",
  "MilwaukeeJunction",
  "MedburyPark",
  "CulturalCenter",
  "MedicalCenter",
  "BrewsterHomes",
  "BrushPark",
  "Douglass",
  "Greektown",
  "ForestPark",
  "EasternMarket",
  "LafayettePark",
  "Rivertown",
  "McDougallHunt",
  "PoletownEast",
  "GratiotKettering",
  "GratiotGrand",
  "WestVillage",
  "GoldCoast",
  "PingreePark",
  "IndianVillage",
  "GratiotWoods",
  "JosephBerry",
  "WaterworksPark",
  "MarinaDistrict",
  "BelleIsle",
  "Boynton",
  "OakwoodHeights",
  "CarbonWorks",
  "Springwells",
  "Delray",
  "Midwest",
  "Claytown",
  "MichiganMartin",
  "ChadseyCondon",
  "CentralSouthwest",
  "HubbardFarms",
  "Mexicantown",
  "WestSideIndustrial",
  "HubbardRichard",
  "Corktown",
  "NorthCorktown",
  "CoreCity",
  "Woodbridge",
  "Jeffries",
  "WayneState",
  "Downtown",
  "WestOuterDrive",
  "RougePark",
  "FarWestDetroit",
  "Weatherby",
  "FranklinPark",
  "Warrendale",
  "SouthfieldPlymouth",
  "PlymouthI",
  "JoyCommunity",
  "GardenView",
  "WarrenAve",
  "PlymouthHubbell",
  "WeCareCommunity",
  "Fiskhorn",
  "JoySchaefer",
  "Paveway",
  "PrideArea",
  "GrandRiverI",
  "HappyHomes",
  "BartonMcFarland",
  "AviationSub",
  "NorthwestCommunity",
  "DavisonSchoolcraft",
  "LittlefieldCommunity",
  "OakmanBlvd",
  "RussellWoods",
  "NardinPark",
  "Other",
].sort((a, b) => a.localeCompare(b))
