import {
  Application,
  ApplicationStatus,
  ApplicationSubmissionType,
  IncomePeriod,
  Language,
} from "@bloom-housing/backend-core/types"

const idDefaults = {
  id: "abcd1234",
  createdAt: new Date(),
  updatedAt: new Date(),
}

export const blankApplication: Application = {
  markedAsDuplicate: false,
  ...idDefaults,
  listing: {
    id: "abcd1234",
  },
  applicant: {
    ...idDefaults,
    firstName: "",
    middleName: "",
    lastName: "",
    birthMonth: undefined,
    birthDay: undefined,
    birthYear: undefined,
    emailAddress: "",
    noEmail: false,
    phoneNumber: "",
    phoneNumberType: "",
    noPhone: false,
    workInRegion: undefined,
    address: {
      ...idDefaults,
      street: "",
      street2: "",
      city: "",
      state: "",
      zipCode: "",
      county: "",
      latitude: undefined,
      longitude: undefined,
    },
    workAddress: {
      ...idDefaults,
      street: "",
      street2: "",
      city: "",
      state: "",
      zipCode: "",
      county: "",
      latitude: undefined,
      longitude: undefined,
    },
  },
  additionalPhone: false,
  additionalPhoneNumber: "",
  additionalPhoneNumberType: "",
  contactPreferences: [],
  householdSize: 0,
  housingStatus: "",
  sendMailToMailingAddress: false,
  mailingAddress: {
    ...idDefaults,
    street: "",
    street2: "",
    city: "",
    state: "",
    zipCode: "",
  },
  alternateAddress: {
    ...idDefaults,
    street: "",
    street2: "",
    city: "",
    state: "",
    zipCode: "",
  },
  alternateContact: {
    ...idDefaults,
    type: "",
    otherType: "",
    firstName: "",
    lastName: "",
    agency: "",
    phoneNumber: "",
    emailAddress: "",
    mailingAddress: {
      ...idDefaults,

      street: "",
      city: "",
      state: "",
      zipCode: "",
    },
  },
  accessibility: {
    ...idDefaults,
    mobility: undefined,
    vision: undefined,
    hearing: undefined,
  },
  incomeVouchers: undefined,
  income: undefined,
  incomePeriod: undefined,
  householdMembers: [],
  preferredUnit: [],
  demographics: {
    ...idDefaults,
    race: "",
    ethnicity: "",
    gender: "",
    sexualOrientation: "",
    howDidYouHear: [],
  },
  preferences: [],
  confirmationCode: "",
  status: ApplicationStatus.draft,
  submissionType: ApplicationSubmissionType.electronical,
  language: Language.en,
}

export const filledApplication: Application = {
  markedAsDuplicate: false,
  ...idDefaults,
  listing: {
    id: "abcd1234",
  },
  applicant: {
    ...idDefaults,
    phoneNumber: "(444) 444-4444",
    noPhone: false,
    phoneNumberType: "work",
    workInRegion: "yes",
    address: {
      ...idDefaults,
      street: "Street",
      street2: "Unit",
      city: "City",
      state: "AL",
      zipCode: "90210",
      county: "",
      latitude: null,
      longitude: null,
    },
    workAddress: {
      ...idDefaults,
      street: "Work Street",
      street2: "Work Unit",
      city: "Work City",
      state: "AL",
      zipCode: "90221",
      county: "",
      latitude: null,
      longitude: null,
    },
    firstName: "First Name",
    middleName: "Middle Name",
    lastName: "Last Name",
    birthMonth: "07",
    birthDay: "17",
    birthYear: "1996",
    emailAddress: "test@bloom.com",
    noEmail: false,
  },
  additionalPhone: true,
  additionalPhoneNumber: "(555) 555-5555",
  additionalPhoneNumberType: "home",
  contactPreferences: ["email"],
  householdSize: 2,
  housingStatus: "",
  sendMailToMailingAddress: true,
  mailingAddress: {
    ...idDefaults,
    street: "Mailing Street",
    street2: "Mailing Unit",
    city: "Mailing City",
    state: "AK",
    zipCode: "90220",
  },
  alternateAddress: {
    ...idDefaults,
    street: "",
    street2: "",
    city: "",
    state: "",
    zipCode: "",
  },
  alternateContact: {
    ...idDefaults,
    type: "caseManager",
    firstName: "Alternate Name",
    lastName: "Alternate Last Name",
    agency: "Agency Name",
    phoneNumber: "(333) 333-3333",
    otherType: "Other Relationship",
    emailAddress: "test2@bloom.com",
    mailingAddress: {
      ...idDefaults,
      street: "Contact Street",
      city: "Contact City",
      state: "AK",
      zipCode: "90222",
    },
  },
  accessibility: {
    ...idDefaults,
    mobility: true,
    vision: false,
    hearing: false,
  },
  incomeVouchers: false,
  income: "3000.00",
  incomePeriod: IncomePeriod.perMonth,
  householdMembers: [
    {
      ...idDefaults,
      firstName: "Member Name",
      middleName: "Member Middle Name",
      lastName: "Member Last Name",
      birthMonth: "07",
      birthDay: "17",
      birthYear: "1996",
      emailAddress: "",
      noEmail: null,
      phoneNumber: "",
      phoneNumberType: "",
      noPhone: null,
      address: {
        ...idDefaults,
        street: "Member Street",
        street2: "Member Unit",
        city: "Member City",
        state: "AZ",
        zipCode: "90223",
      },
      workAddress: {
        ...idDefaults,
        street: "Member Work Street",
        street2: "Member Work Unit",
        city: "Member Work City",
        state: "AR",
        zipCode: "90224",
      },
      sameAddress: "no",
      relationship: "spouse",
      workInRegion: "yes",
    },
  ],
  preferredUnit: [
    {
      ...idDefaults,
      id: "dff3ff70-7085-4dab-afd9-de4b33e0ec1e",
      name: "1 Bedroom",
      numBedrooms: 1,
    },
  ],
  demographics: {
    ...idDefaults,
    race: "white",
    ethnicity: "hispanicLatino",
    gender: "female",
    sexualOrientation: "bisexual",
    howDidYouHear: ["alamedaCountyHCDWebsite", "developerWebsite"],
  },
  preferences: [
    {
      key: "liveWork",
      claimed: true,
      options: [
        {
          key: "live",
          checked: true,
          extraData: [],
        },
        {
          key: "work",
          checked: true,
          extraData: [],
        },
      ],
    },
  ],
  confirmationCode: "",
  status: ApplicationStatus.draft,
  submissionType: ApplicationSubmissionType.electronical,
  language: Language.en,
}

export const applicationStepOrder = [
  { name: "chooseLanguage", route: "/applications/start/choose-language" },
  { name: "whatToExpect", route: "/applications/start/what-to-expect" },
  { name: "primaryApplicantName", route: "/applications/contact/name" },
  { name: "primaryApplicantAddress", route: "/applications/contact/address" },
  { name: "alternateContactType", route: "/applications/contact/alternate-contact-type" },
  { name: "alternateContactName", route: "/applications/contact/alternate-contact-name" },
  { name: "alternateContactInfo", route: "/applications/contact/alternate-contact-contact" },
  { name: "liveAlone", route: "/applications/household/live-alone" },
  { name: "householdMemberInfo", route: "/applications/household/members-info" },
  { name: "addMembers", route: "/applications/household/add-members" },
  { name: "preferredUnitSize", route: "/applications/household/preferred-units" },
  { name: "adaHouseholdMembers", route: "/applications/household/ada" },
  { name: "vouchersSubsidies", route: "/applications/financial/vouchers" },
  { name: "income", route: "/applications/financial/income" },
  { name: "preferencesAll", route: "/applications/preferences/all" },
  { name: "generalPool", route: "/applications/preferences/general" },
  { name: "demographics", route: "/applications/review/demographics" },
  { name: "summary", route: "/applications/review/summary" },
  { name: "terms", route: "/applications/review/terms" },
]

const idkkk = {
  loaded: true,
  autofilled: false,
  completedSections: 0,
  submissionType: "electronical",
  language: "en",
  acceptedTerms: false,
  status: "submitted",
  applicant: {
    firstName: "First Name",
    middleName: "Middle Name",
    lastName: "Last Name",
    birthMonth: "07",
    birthDay: "17",
    birthYear: "1996",
    emailAddress: "test@bloom.com",
    noEmail: false,
    phoneNumber: "",
    phoneNumberType: "",
    noPhone: false,
    workInRegion: null,
    address: {
      street: "",
      street2: "",
      city: "",
      state: "",
      zipCode: "",
      county: "",
      latitude: null,
      longitude: null,
    },
    workAddress: {
      street: "",
      street2: "",
      city: "",
      state: "",
      zipCode: "",
      county: "",
      latitude: null,
      longitude: null,
    },
  },
  additionalPhone: false,
  additionalPhoneNumber: "",
  additionalPhoneNumberType: "",
  contactPreferences: [],
  householdSize: 0,
  housingStatus: "",
  sendMailToMailingAddress: false,
  mailingAddress: { street: "", street2: "", city: "", state: "", zipCode: "" },
  alternateAddress: { street: "", street2: "", city: "", state: "", zipCode: "" },
  alternateContact: {
    type: "",
    otherType: "",
    firstName: "",
    lastName: "",
    agency: "",
    phoneNumber: "",
    emailAddress: null,
    mailingAddress: { street: "", city: "", state: "", zipCode: "" },
  },
  accessibility: { mobility: null, vision: null, hearing: null },
  incomeVouchers: null,
  income: null,
  incomePeriod: null,
  householdMembers: [],
  preferredUnit: [],
  demographics: { ethnicity: "", race: "", gender: "", sexualOrientation: "", howDidYouHear: [] },
  preferences: [],
  confirmationId: "",
}
