import { ListingCreateDto } from "../../../src/listings/dto/listing-create.dto"
import { ListingReviewOrder, ListingStatus } from "../../../types"
import { BaseEntity } from "typeorm"

export function makeTestListing(jurisdictionId: string): Omit<ListingCreateDto, keyof BaseEntity> {
  return {
    jurisdiction: {
      id: jurisdictionId,
    },
    additionalApplicationSubmissionNotes: null,
    digitalApplication: false,
    commonDigitalApplication: false,
    paperApplication: false,
    referralOpportunity: false,
    assets: [],
    applicationDueDate: null,
    applicationOpenDate: new Date(0),
    applicationFee: "20",
    applicationOrganization: "Application Organization",
    applicationPickUpAddressOfficeHours: "Custom pick up address office hours text",
    applicationPickUpAddressType: null,
    applicationDropOffAddressOfficeHours: null,
    applicationDropOffAddressType: null,
    applicationMailingAddressType: null,
    buildingSelectionCriteria: "https://www.example.com",
    costsNotIncluded: "Custom costs not included text",
    creditHistory: "Custom credit history text",
    criminalBackground: "Custom criminal background text",
    depositMin: "500",
    depositMax: "500",
    depositHelperText: null,
    disableUnitsAccordion: true,
    leasingAgentEmail: "hello@exygy.com",
    leasingAgentName: "Leasing Agent Name",
    leasingAgentOfficeHours: "Custom leasing agent office hours",
    leasingAgentPhone: "(415) 992-7251",
    leasingAgentTitle: "Leasing Agent Title",
    name: "Test: Default, FCFS",
    postmarkedApplicationsReceivedByDate: null,
    programRules: "Custom program rules text",
    rentalAssistance: "Custom rental assistance text",
    rentalHistory: "Custom rental history text",
    requiredDocuments: "Custom required documents text",
    specialNotes: "Custom special notes text",
    waitlistCurrentSize: null,
    waitlistMaxSize: null,
    whatToExpect: "Custom what to expect text",
    status: ListingStatus.pending,
    reviewOrderType: ListingReviewOrder.firstComeFirstServe,
    displayWaitlistSize: false,
    reservedCommunityDescription: null,
    reservedCommunityMinAge: null,
    resultLink: null,
    isWaitlistOpen: false,
    waitlistOpenSpots: null,
    customMapPin: null,
    applicationMethods: [],
    applicationPickUpAddress: {
      placeName: null,
      city: "San Francisco",
      county: null,
      state: "CA",
      street: "548 Market Street",
      street2: "Suite #59930",
      zipCode: "94104",
      latitude: 37.789673,
      longitude: -122.40151,
    },
    applicationDropOffAddress: null,
    applicationMailingAddress: null,
    buildingSelectionCriteriaFile: null,
    events: [],
    images: [],
    leasingAgentAddress: {
      placeName: null,
      city: "San Francisco",
      county: null,
      state: "CA",
      street: "548 Market Street",
      street2: "Suite #59930",
      zipCode: "94104",
      latitude: 37.789673,
      longitude: -122.40151,
    },
    leasingAgents: [],
    listingPrograms: [],
    listingPreferences: [],
    reservedCommunityType: null,
    result: null,
    units: [],
    accessibility: "Custom accessibility text",
    amenities: "Custom property amenities text",
    buildingAddress: {
      placeName: null,
      city: "San Francisco",
      county: null,
      state: "CA",
      street: "548 Market Street",
      street2: "Suite #59930",
      zipCode: "94104",
      latitude: 37.789673,
      longitude: -122.40151,
    },
    buildingTotalUnits: 100,
    developer: "Developer",
    householdSizeMax: null,
    householdSizeMin: null,
    neighborhood: "Custom neighborhood text",
    petPolicy: "Custom pet text",
    smokingPolicy: "Custom smoking text",
    unitsAvailable: 2,
    unitAmenities: "Custom unit amenities text",
    servicesOffered: "Custom services offered text",
    yearBuilt: 2021,
    countyCode: "Alameda",
  }
}
