{
 "title": "API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Request Duration P99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(path, response_code, protocol, le, method) (rate(metrics_interceptor_request_duration_ms_bucket{job=\"bloom-api\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Rate per second",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(metrics_interceptor_request_counter_total{job=\"bloom-api\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Error Rate per second",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(metrics_interceptor_request_counter_total{job=\"bloom-api\", response_code=~\"^[45][0-9]{2}$\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prisma Query Duration P99",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.99, sum by(le) (rate(prisma_client_queries_duration_histogram_ms_bucket{job=\"prisma_metrics\"}[$__rate_interval]))), \"query\", \"prisma_client_duration_p99\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum by(le) (rate(prisma_datasource_queries_duration_histogram_ms_bucket[$__rate_interval]))), \"query\", \"prisma_sql_duration_p99\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prisma Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "label_replace(sum(rate(prisma_client_queries_total[$__rate_interval])), \"query\", \"prisma_client_queries\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(rate(prisma_datasource_queries_total[$__rate_interval])), \"query\", \"prisma_sql_queries\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}