{
 "title": "Partners Site",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Partners Site Request Duration P99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method, path, response_code) (rate(middleware_request_duration_ms_bucket{job=\"bloom-site-partners\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partners Site Request Rate per second",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(middleware_request_counter_total{job=\"bloom-site-partners\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partners Site Error Rate per second",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(middleware_request_counter_total{job=\"bloom-site-partners\", response_code=~\"^[45][0-9]{2}$\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}