{
 "title": "API/Prisma",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prisma Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(__name__) (prisma_pool_connections_open)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__name__) (prisma_pool_connections_busy)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__name__) (prisma_pool_connections_idle)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prisma Connections opened/closed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(__name__) (prisma_pool_connections_opened_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__name__) (prisma_pool_connections_closed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prisma Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "label_replace(sum(rate(prisma_client_queries_total[$__rate_interval])), \"query\", \"prisma_client_queries\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(rate(prisma_datasource_queries_total[$__rate_interval])), \"query\", \"prisma_sql_queries\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prisma Query Duration P99",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.99, sum by(le) (rate(prisma_client_queries_duration_histogram_ms_bucket[$__rate_interval]))), \"query\", \"prisma_client_duration_p99\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum by(le) (rate(prisma_datasource_queries_duration_histogram_ms_bucket[$__rate_interval]))), \"query\", \"prisma_sql_duration_p99\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}