-- AlterTable
ALTER TABLE "jurisdictions" 
ADD COLUMN "what_to_expect" TEXT NOT NULL DEFAULT '<p>If you are interested in applying for this property, please get in touch in one of these ways:</p><ul><li><p>Phone</p></li><li><p>Email</p></li><li><p>In-person</p></li><li><p>In some instances, the property has a link directly to an application</p></li></ul><p>Once you contact a property, ask if they have any available units if you are looking to move in immediately.</p><p><strong>Waitlists</strong>:</p><p>If none are available, but you are still interested in eventually living at the property, ask how you can be placed on their waitlist.</p>',
ADD COLUMN "what_to_expect_additional_text" TEXT NOT NULL DEFAULT '<ul><li><p>Property staff should walk you through the process to get on their waitlist.</p></li><li><p>You can be on waitlists for multiple properties, but you will need to contact each one of them to begin that process.</p></li><li><p>Even if you are on a waitlist, it can take months or over a year to get an available unit for that building.</p></li><li><p>Many properties that are affordable because of government funding or agreements have long waitlists. If you are on a waitlist for a property, you should contact the property on a regular basis to see if any units are available.</p></li></ul>',
ADD COLUMN "what_to_expect_under_construction" TEXT NOT NULL DEFAULT 'This property is still under construction by the property owners. If you sign up for notifications through Detroit Home Connect, we will send you updates when this property has opened up applications for residents. You can also check back later to this page for updates.';
UPDATE "listings" 
SET "what_to_expect" = CASE
    WHEN "marketing_type" = 'marketing' THEN '<p>If you are interested in applying for this property, please get in touch in one of these ways:</p><ul><li><p>Phone</p></li><li><p>Email</p></li><li><p>In-person</p></li><li><p>In some instances, the property has a link directly to an application</p></li></ul><p>Once you contact a property, ask if they have any available units if you are looking to move in immediately.</p><p><strong>Waitlists</strong>:</p><p>If none are available, but you are still interested in eventually living at the property, ask how you can be placed on their waitlist.</p>'
    WHEN "marketing_type" = 'comingSoon' THEN 'This property is still under construction by the property owners. If you sign up for notifications through Detroit Home Connect, we will send you updates when this property has opened up applications for residents. You can also check back later to this page for updates.'
    END,
"what_to_expect_additional_text" = CASE
    WHEN "marketing_type" = 'marketing' THEN '<ul><li><p>Property staff should walk you through the process to get on their waitlist.</p></li><li><p>You can be on waitlists for multiple properties, but you will need to contact each one of them to begin that process.</p></li><li><p>Even if you are on a waitlist, it can take months or over a year to get an available unit for that building.</p></li><li><p>Many properties that are affordable because of government funding or agreements have long waitlists. If you are on a waitlist for a property, you should contact the property on a regular basis to see if any units are available.</p></li></ul>'
    WHEN "marketing_type" = 'comingSoon' THEN ''
    END;