import { Button, Dialog } from "@bloom-housing/ui-seeds"

export const AiPermissionModal = ({
  showOnboardingModal,
  setShowOnboardingModal,
  handleConfirmGenAI,
}: {
  showOnboardingModal: boolean
  setShowOnboardingModal: (show: boolean) => void
  handleConfirmGenAI: () => void
}) => {
  return (
    <Dialog
      isOpen={showOnboardingModal}
      onClose={() => setShowOnboardingModal(false)}
      ariaLabelledBy="genai-onboarding-header"
      ariaDescribedBy="genai-onboarding-content"
    >
      <Dialog.Header id="genai-onboarding-header">Enable AI Insights</Dialog.Header>
      <Dialog.Content id="genai-onboarding-content">
        <div className="space-y-4">
          <div className="flex items-start space-x-3">
            <div className="flex-shrink-0 w-12 h-12 bg-amber-100 rounded-full flex items-center justify-center">
              <svg
                className="w-6 h-6 text-amber-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.732-.833-2.5 0L4.314 16.5c-.77.833.192 2.5 1.732 2.5z"
                />
              </svg>
            </div>
            <div className="flex-1">
              <h4 className="font-semibold text-gray-900 mb-2">
                Important Notice About AI-Generated Content
              </h4>
              <div className="space-y-3 text-sm text-gray-700">
                <p>
                  <strong>AI outputs can be unpredictable:</strong> The insights provided are
                  generated by artificial intelligence and may contain errors, biases, or incomplete
                  information.
                </p>
                <p>
                  <strong>Always verify results:</strong> All AI-generated insights should be
                  independently verified and researched before making any decisions or taking
                  action.
                </p>
                <p>
                  <strong>Use as a starting point:</strong> These insights are meant to supplement,
                  not replace, professional judgment and thorough analysis.
                </p>
                <p>
                  <strong>No liability:</strong> The AI insights are provided for informational
                  purposes only and should not be relied upon as the sole basis for important
                  decisions.
                </p>
              </div>
            </div>
          </div>

          <div className="bg-gray-50 rounded-lg p-4 border">
            <div className="flex items-center space-x-2 mb-2">
              <svg
                className="w-5 h-5 text-blue-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              <span className="font-medium text-gray-900">Best Practices</span>
            </div>
            <ul className="text-sm text-gray-700 space-y-1 list-disc list-inside">
              <li>Cross-reference AI insights with official data sources</li>
              <li>Consult with subject matter experts</li>
              <li>Consider multiple perspectives and data points</li>
              <li>Document your verification process</li>
            </ul>
          </div>
        </div>
      </Dialog.Content>
      <Dialog.Footer>
        <Button variant="primary" onClick={handleConfirmGenAI} size="sm">
          I Understand - Enable AI Insights
        </Button>
        <Button variant="primary-outlined" onClick={() => setShowOnboardingModal(false)} size="sm">
          Cancel
        </Button>
      </Dialog.Footer>
    </Dialog>
  )
}
