/* eslint-env node */

module.exports = {
  important: true,
  purge: false,
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1200px",
      xl: "1280px",
      print: { raw: "print" },
    },
    fontSize: {
      "2xs": ".6875rem",
      xs: ".75rem",
      sm: ".8125rem",
      tiny: ".875rem",
      base: "1rem",
      lg: "1.25rem",
      xl: "1.375rem",
      "2xl": "1.5rem",
      "3xl": "1.625rem",
      "4xl": "2rem",
      "5xl": "2.5rem",
      "6xl": "3rem",
      "6.5xl": "4rem",
      "7xl": "4.5rem",
    },
    fontFamily: {
      sans: "var(--bloom-font-sans)",
      serif: "var(--bloom-font-serif)",
      "alt-sans": "var(--bloom-font-alt-sans)",
    },
    colors: {
      primary: "var(--bloom-color-primary)",
      "primary-dark": "var(--bloom-color-primary-dark)",
      "primary-darker": "var(--bloom-color-primary-darker)",
      "primary-light": "var(--bloom-color-primary-light)",
      "primary-lighter": "var(--bloom-color-primary-lighter)",
      secondary: "#0067be",
      alert: "#E41D3D",
      "alert-light": "#F9D2D8",
      "alert-dark": "#B21D38",
      success: "#2E8540",
      "success-light": "#B4E5BE",
      "success-dark": "#216E1F",
      warn: "#FDB81E",
      "warn-light": "#FEE8B6",
      "warn-dark": "#E5A000",
      "accent-cool": "var(--bloom-color-accent-cool)",
      "accent-cool-light": "var(--bloom-color-accent-cool-light)",
      "accent-cool-dark": "var(--bloom-color-accent-cool-dark)",
      "accent-warm": "var(--bloom-color-accent-warm)",
      "accent-warm-dark": "var(--bloom-color-accent-warm-dark)",
      "accent-warm-light": "var(--bloom-color-accent-warm-light)",
      "accent-warm-lighter": "var(--bloom-color-accent-warm-lighter)",
      royal: "#B85ED5",
      "royal-light": "#EED7F5",
      "royal-dark": "#A131C6",
      lush: "#99CD00",
      "lush-light": "#F2FFCD",
      "lush-dark": "#7CA700",
      white: "#FFFFFF",
      black: "#000000",
      blue: {
        800: "#205493",
        700: "#0067be",
        600: "#0077DA",
        300: "#DAEEFF",
        200: "#F5F8F9",
      },
      red: {
        700: "#E41D3D",
        300: "#F9D2D8",
      },
      yellow: {
        700: "#FDB81E",
        300: "#FEE8B6",
      },
      green: {
        700: "#2E8540",
        300: "#B4E5BE",
      },
      teal: {
        700: "#2E8540",
        300: "#B4E5BE",
      },
      gray: {
        950: "#242C2E",
        900: "#222222",
        850: "#333333",
        800: "#30383A",
        750: "#555555",
        700: "#767676",
        600: "#999999",
        550: "#AAAAAA",
        500: "#CCCCCC",
        450: "#DEDEE0",
        400: "#EFEFEF",
        300: "#F6F6F6",
        200: "#F7F7F7",
        100: "#F9F9F9",
      },
    },
    letterSpacing: {
      tightest: "-.075em",
      tighter: "-.05em",
      tight: "-.025em",
      normal: "0",
      wide: ".025em",
      wider: ".05em",
      widest: ".12em",
      ultrawide: ".25em",
    },
    extend: {
      borderColor: (theme) => ({
        DEFAULT: theme("colors.gray.450", "currentColor"),
      }),
      inset: {
        4: "1rem",
        "-10": "-2.5rem",
      },
    },
  },
}
