/* eslint-env node */

module.exports = {
  important: true,
  purge: false,
  plugins: [require("tailwindcss-rtl")],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1200px",
      xl: "1280px",
      "2xl": "1440px",
      print: { raw: "print" },
    },
    fontSize: {
      "3xs": "var(--bloom-font-size-3xs)",
      "2xs": "var(--bloom-font-size-2xs)",
      xs: "var(--bloom-font-size-xs)",
      sm: "var(--bloom-font-size-sm)",
      base: "var(--bloom-font-size-base)",
      lg: "var(--bloom-font-size-lg)",
      xl: "var(--bloom-font-size-xl)",
      "2xl": "var(--bloom-font-size-2xl)",
      "3xl": "var(--bloom-font-size-3xl)",
      "4xl": "var(--bloom-font-size-4xl)",
      "5xl": "var(--bloom-font-size-5xl)",
      "6xl": "var(--bloom-font-size-6xl)",
      "7xl": "var(--bloom-font-size-7xl)",
    },
    fontFamily: {
      sans: "var(--bloom-font-sans)",
      serif: "var(--bloom-font-serif)",
      "alt-sans": "var(--bloom-font-alt-sans)",
    },
    colors: {
      primary: "var(--bloom-color-primary)",
      "primary-dark": "var(--bloom-color-primary-dark)",
      "primary-darker": "var(--bloom-color-primary-darker)",
      "primary-light": "var(--bloom-color-primary-light)",
      "primary-lighter": "var(--bloom-color-primary-lighter)",
      alert: "var(--bloom-color-alert)",
      "alert-light": "var(--bloom-color-alert-light)",
      "alert-lighter": "var(--bloom-color-alert-lighter)",
      "alert-dark": "var(--bloom-color-alert-dark)",
      "alert-darker": "var(--bloom-color-alert-darker)",
      success: "var(--bloom-color-success)",
      "success-light": "var(--bloom-color-success-light)",
      "success-lighter": "var(--bloom-color-success-lighter)",
      "success-dark": "var(--bloom-color-success-dark)",
      "success-darker": "var(--bloom-color-success-darker)",
      warn: "var(--bloom-color-warn)",
      "warn-light": "var(--bloom-color-warn-light)",
      "warn-lighter": "var(--bloom-color-warn-lighter)",
      "warn-dark": "var(--bloom-color-warn-dark)",
      "warn-darker": "var(--bloom-color-warn-darker)",
      text: "var(--bloom-text-color)",
      "text-light": "var(--bloom-text-color-light)",
      "text-lighter": "var(--bloom-text-color-lighter)",
      "text-dark": "var(--bloom-text-color-dark)",
      "text-darker": "var(--bloom-text-color-darker)",
      "accent-cool": "var(--bloom-color-accent-cool)",
      "accent-cool-light": "var(--bloom-color-accent-cool-light)",
      "accent-cool-lighter": "var(--bloom-color-accent-cool-lighter)",
      "accent-cool-dark": "var(--bloom-color-accent-cool-dark)",
      "accent-cool-darker": "var(--bloom-color-accent-cool-darker)",
      "accent-warm": "var(--bloom-color-accent-warm)",
      "accent-warm-light": "var(--bloom-color-accent-warm-light)",
      "accent-warm-lighter": "var(--bloom-color-accent-warm-lighter)",
      "accent-warm-dark": "var(--bloom-color-accent-warm-dark)",
      "accent-warm-darker": "var(--bloom-color-accent-warm-darker)",
      white: "var(--bloom-color-white)",
      black: "var(--bloom-color-black)",
      blue: {
        900: "var(--bloom-color-blue-900)",
        700: "var(--bloom-color-blue-700)",
        500: "var(--bloom-color-blue-500)",
        300: "var(--bloom-color-blue-300)",
        100: "var(--bloom-color-blue-100)",
      },
      red: {
        900: "var(--bloom-color-red-900)",
        700: "var(--bloom-color-red-700)",
        500: "var(--bloom-color-red-500)",
        300: "var(--bloom-color-red-300)",
        100: "var(--bloom-color-red-100)",
      },
      yellow: {
        900: "var(--bloom-color-yellow-900)",
        700: "var(--bloom-color-yellow-700)",
        500: "var(--bloom-color-yellow-500)",
        300: "var(--bloom-color-yellow-300)",
        100: "var(--bloom-color-yellow-100)",
      },
      green: {
        900: "var(--bloom-color-green-900)",
        700: "var(--bloom-color-green-700)",
        500: "var(--bloom-color-green-500)",
        300: "var(--bloom-color-green-300)",
        100: "var(--bloom-color-green-100)",
      },
      gray: {
        950: "var(--bloom-color-gray-950)",
        900: "var(--bloom-color-gray-900)",
        850: "var(--bloom-color-gray-850)",
        800: "var(--bloom-color-gray-800)",
        750: "var(--bloom-color-gray-750)",
        700: "var(--bloom-color-gray-700)",
        650: "var(--bloom-color-gray-650)",
        600: "var(--bloom-color-gray-600)",
        550: "var(--bloom-color-gray-550)",
        500: "var(--bloom-color-gray-500)",
        450: "var(--bloom-color-gray-450)",
        400: "var(--bloom-color-gray-400)",
        300: "var(--bloom-color-gray-300)",
        200: "var(--bloom-color-gray-200)",
        100: "var(--bloom-color-gray-100)",
      },
    },
    letterSpacing: {
      tightest: "var(--bloom-letter-spacing-tightest)",
      tighter: "var(--bloom-letter-spacing-tighter)",
      tight: "var(--bloom-letter-spacing-tight)",
      normal: "0",
      wide: "var(--bloom-letter-spacing-wide)",
      wider: "var(--bloom-letter-spacing-wider)",
      widest: "var(--bloom-letter-spacing-widest)",
      ultrawide: "var(--bloom-letter-spacing-ultrawide)",
    },
    extend: {
      borderColor: (theme) => ({
        DEFAULT: theme("colors.gray.450", "currentColor"),
      }),
      inset: {
        4: "1rem",
        "-10": "-2.5rem",
      },
    },
  },
}
