import {
  ApplicationMethodsTypeEnum,
  ListingEventsTypeEnum,
  ListingsStatusEnum,
  Prisma,
  ReviewOrderTypeEnum,
} from '@prisma/client';
import dayjs from 'dayjs';

export const districtViewApartments: Prisma.ListingsCreateInput = {
  additionalApplicationSubmissionNotes: null,
  digitalApplication: true,
  commonDigitalApplication: true,
  paperApplication: false,
  referralOpportunity: false,
  assets: [],
  accessibility: null,
  amenities: null,
  buildingTotalUnits: 0,
  developer: 'ABS Housing',
  householdSizeMax: 0,
  householdSizeMin: 0,
  neighborhood: null,
  petPolicy: 'Pets are not permitted on the property. ',
  smokingPolicy: null,
  unitAmenities: 'Each unit comes with included central AC.',
  servicesOffered: null,
  yearBuilt: 2021,
  applicationDueDate: dayjs(new Date()).add(30, 'days').toDate(),
  applicationOpenDate: dayjs(new Date()).subtract(7, 'days').toDate(),
  applicationFee: '35',
  applicationOrganization: null,
  applicationPickUpAddressOfficeHours: null,
  applicationPickUpAddressType: null,
  applicationDropOffAddressOfficeHours: null,
  applicationDropOffAddressType: null,
  applicationMailingAddressType: null,
  applicationMethods: {
    create: {
      type: ApplicationMethodsTypeEnum.ExternalLink,
      externalReference: 'https://example.com/application',
    },
  },
  buildingSelectionCriteria: null,
  costsNotIncluded: null,
  creditHistory: null,
  criminalBackground: null,
  depositMin: '500',
  depositMax: '0',
  depositHelperText: "Deposit will not exceed one month's rent",
  disableUnitsAccordion: false,
  leasingAgentEmail: 'sgates@abshousing.com',
  leasingAgentName: 'Samuel Gates',
  leasingAgentOfficeHours: null,
  leasingAgentPhone: '(888) 888-8888',
  leasingAgentTitle: 'Property Manager',
  name: 'District View Apartments',
  postmarkedApplicationsReceivedByDate: null,
  programRules: null,
  rentalAssistance:
    'Housing Choice Vouchers, Section 8 and other valid rental assistance programs will be considered for this property. In the case of a valid rental subsidy, the required minimum income will be based on the portion of the rent that the tenant pays after use of the subsidy.',
  rentalHistory: null,
  requiredDocuments: null,
  specialNotes: null,
  waitlistCurrentSize: null,
  waitlistMaxSize: null,
  whatToExpect:
    'Applicants will be contacted by the property agent in rank order until vacancies are filled. All of the information that you have provided will be verified and your eligibility confirmed. Your application will be removed from the waitlist if you have made any fraudulent statements. If we cannot verify a housing preference that you have claimed, you will not receive the preference but will not be otherwise penalized. Should your application be chosen, be prepared to fill out a more detailed application and provide required supporting documents.',
  status: ListingsStatusEnum.active,
  reviewOrderType: ReviewOrderTypeEnum.lottery,
  lotteryOptIn: true,
  displayWaitlistSize: false,
  reservedCommunityDescription: null,
  reservedCommunityMinAge: null,
  resultLink: null,
  isWaitlistOpen: false,
  waitlistOpenSpots: null,
  customMapPin: false,
  contentUpdatedAt: new Date(),
  publishedAt: new Date(),
  listingsApplicationPickUpAddress: undefined,
  listingsApplicationDropOffAddress: undefined,
  listingsApplicationMailingAddress: undefined,
  reservedCommunityTypes: undefined,
  listingEvents: {
    create: [
      {
        type: ListingEventsTypeEnum.publicLottery,
        startDate: new Date(),
        startTime: new Date(),
        endTime: new Date(),
      },
    ],
  },
  listingFeatures: undefined,
  listingUtilities: undefined,
};
