import {
  ApplicationMultiselectQuestion,
  ApplicationStatusEnum,
  ApplicationSubmissionTypeEnum,
  LanguagesEnum,
} from "../types/backend-swagger"

export const blankApplication = {
  loaded: false,
  autofilled: false,
  completedSections: 0,
  submissionType: ApplicationSubmissionTypeEnum.electronical,
  language: LanguagesEnum.en,
  acceptedTerms: false,
  status: ApplicationStatusEnum.submitted,
  applicant: {
    // orderId: undefined,
    firstName: "",
    middleName: "",
    lastName: "",
    birthMonth: "",
    birthDay: "",
    birthYear: "",
    emailAddress: null,
    noEmail: false,
    phoneNumber: "",
    phoneNumberType: "",
    noPhone: false,
    fullTimeStudent: null,
    applicantAddress: {
      street: "",
      street2: "",
      city: "",
      state: "",
      zipCode: "",
      county: "",
      latitude: undefined,
      longitude: undefined,
    },
  },
  additionalPhone: false,
  additionalPhoneNumber: "",
  additionalPhoneNumberType: "",
  householdSize: 0,
  housingStatus: "",
  sendMailToMailingAddress: false,
  applicationsMailingAddress: {
    street: "",
    street2: "",
    city: "",
    state: "",
    zipCode: "",
  },
  applicationsAlternateAddress: {
    street: "",
    street2: "",
    city: "",
    state: "",
    zipCode: "",
  },
  alternateContact: {
    type: "",
    otherType: "",
    firstName: "",
    lastName: "",
    agency: "",
    phoneNumber: "",
    emailAddress: null,
    address: {
      street: "",
      street2: "",
      city: "",
      state: "",
      zipCode: "",
    },
  },
  accessibility: {
    mobility: null,
    vision: null,
    hearing: null,
  },
  householdExpectingChanges: null,
  householdStudent: null,
  incomeVouchers: [],
  income: null,
  incomePeriod: null,
  householdMember: [],
  preferredUnitTypes: [],
  demographics: {
    ethnicity: "",
    race: [],
    gender: "",
    sexualOrientation: "",
    spokenLanguage: "",
    howDidYouHear: [],
  },
  preferences: [] as ApplicationMultiselectQuestion[],
  programs: [] as ApplicationMultiselectQuestion[],
  confirmationCode: "",
  id: "",
}
