name: Partners Cypress (LA)

on:
  pull_request:
    branches:
      - main
env:
  PORT: 3100
  EMAIL_API_KEY: 'SOME-LONG-SECRET-KEY'
  APP_SECRET: 'SOME-LONG-SECRET-KEY'
  CLOUDINARY_SECRET: CLOUDINARY_SECRET
  CLOUDINARY_KEY: CLOUDINARY_KEY
  CLOUDINARY_SIGNED_PRESET: "signedpreset"
  CLOUDINARY_CLOUD_NAME: "exygy"
  PARTNERS_PORTAL_URL: http://localhost:3001
  DATABASE_URL: postgres://bloom-dev:bloom@127.0.0.1:5432/bloom
  TEST_DATABASE_URL: postgres://bloom-dev:bloom@127.0.0.1:5432/bloom_test
  BACKEND_API_BASE: http://localhost:3100
  LISTINGS_QUERY: /listings
  NEXTJS_PORT: 3001
  LISTINGS_ENDPOINT_PATH: /listings
  MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
  FEATURE_LISTINGS_APPROVAL: "TRUE"
  API_PASS_KEY: "some-key-here"


jobs:
  partners-cypress-la:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: bloom-dev
          POSTGRES_PASSWORD: bloom
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Check postgres
        run: pg_isready -h 127.0.0.1 -p ${{ job.services.postgres.ports[5432] }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: yarn in root dir
        run: yarn

      - name: yarn in api dir
        working-directory: ./api
        run: yarn

      - name: Check postgres
        run: pg_isready -h 127.0.0.1 -p 5432

      - name: Create DB
        run: psql -U bloom-dev -c 'CREATE DATABASE bloom;'
        env:
          PGHOST: 127.0.0.1
          PGPASSWORD: bloom

      - name: Setup backend
        run: yarn test:backend:new:dbsetup:withseed
        env:
          PGHOST: 127.0.0.1
          PGPASSWORD: bloom
          PGUSER: bloom-dev

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./sites/partners
          spec: cypress/e2e/listings-approval/*.spec.ts
          build: yarn build
          start: yarn dev:new-backend, yarn start
          wait-on: 'http://localhost:3100/'
          record: false # set this value to true to record videos in cypress cloud for debugging purposes - skip passing tests
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.PARTNERS_CYPRESS_RECORD_KEY }}
       